name: education_system
description: Education system for federal college of education ibiono

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ffi: ^2.0.1
  flutter_rust_bridge: 2.0.0-dev.15
  meta: ^1.8.0
  uuid: ^4.3.2
  get_it: ^7.6.6
  dio: ^5.4.0
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  intl: ^0.19.0
  pretty_dio_logger: ^1.3.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  surrealdb: ^0.7.0
#  crypto: ^3.0.3
  bcrypt: ^1.1.3
  rust_builder:
    path: rust_builder

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  ffigen: 10.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #  - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
